### ISSUE TITLE
Add genomicsdb-workspace output for ImportGenomicsDB tool

### ISSUE THREAD

**Issue by ThomasHickman** [yejinyou/PY#15]
ImportGenomicsDB produces a folder referenced to by `genomicsdb-workspace-path`. This is not specified as an output parameter

**Comment by keysmashes** [comment]
I think this is now done. This is the extra cwl that now gets inserted:

```yaml
outputs:
- id: genomicsdb-workspace-path-out
  doc: Resulting GenomicsDB workspace (corresponding to the input genomicsdb-workspace-path).
  type: Directory
  outputBinding:
    glob: $(inputs['genomicsdb-workspace-path'])
```

The spec isn't too explicit about it, but I *think* it's allowed to have `type: Directory` on an output.
